//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szotar.WindowsForms.Resources {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class LanguagePair {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal LanguagePair() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szotar.WindowsForms.Resources.Strings.LanguagePair", typeof(LanguagePair).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Whoever originally wrote or compiled the dictionary..
		/// </summary>
		internal static string Author_Description {
			get {
				return ResourceManager.GetString("Author.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Author.
		/// </summary>
		internal static string Author_Name {
			get {
				return ResourceManager.GetString("Author.Name", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The human readable name of the language of the “left” half of the dictionary..
		/// </summary>
		internal static string FirstLanguage_Description {
			get {
				return ResourceManager.GetString("FirstLanguage.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to First Language.
		/// </summary>
		internal static string FirstLanguage_Name {
			get {
				return ResourceManager.GetString("FirstLanguage.Name", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The ISO-639 language code of the first language. This is used to automatically switch search directions when the Windows input language changes..
		/// </summary>
		internal static string FirstLanguageCode_Description {
			get {
				return ResourceManager.GetString("FirstLanguageCode.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to First Language ISO code.
		/// </summary>
		internal static string FirstLanguageCode_Name {
			get {
				return ResourceManager.GetString("FirstLanguageCode.Name", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The human readable name of the language of the “left” half of the dictionary, in the other language..
		/// </summary>
		internal static string FirstLanguageReverse_Description {
			get {
				return ResourceManager.GetString("FirstLanguageReverse.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to First Language (in the second language).
		/// </summary>
		internal static string FirstLanguageReverse_Name {
			get {
				return ResourceManager.GetString("FirstLanguageReverse.Name", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name of the dictionary. This isn&apos;t actually used anywhere, as far as I can tell, but you might as well set it, in case it becomes useful..
		/// </summary>
		internal static string Name_Description {
			get {
				return ResourceManager.GetString("Name.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		internal static string Name_Name {
			get {
				return ResourceManager.GetString("Name.Name", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The human readable name of the language of the “left” half of the dictionary..
		/// </summary>
		internal static string SecondLanguage_Description {
			get {
				return ResourceManager.GetString("SecondLanguage.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Second Language.
		/// </summary>
		internal static string SecondLanguage_Name {
			get {
				return ResourceManager.GetString("SecondLanguage.Name", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The ISO-639 language code of the second language. This is used to automatically switch search directions when the Windows input language changes..
		/// </summary>
		internal static string SecondLanguageCode_Description {
			get {
				return ResourceManager.GetString("SecondLanguageCode.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to First Language ISO code.
		/// </summary>
		internal static string SecondLanguageCode_Name {
			get {
				return ResourceManager.GetString("SecondLanguageCode.Name", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The human readable name of the language of the “right” half of the dictionary, in the first language..
		/// </summary>
		internal static string SecondLanguageReverse_Description {
			get {
				return ResourceManager.GetString("SecondLanguageReverse.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Second Language (in the first language).
		/// </summary>
		internal static string SecondLanguageReverse_Name {
			get {
				return ResourceManager.GetString("SecondLanguageReverse.Name", resourceCulture);
			}
		}
	}
}
