//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szotar.WindowsForms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szotar.WindowsForms.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asdsad.
        /// </summary>
        internal static string asdasdas {
            get {
                return ResourceManager.GetString("asdasdas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program database cannot be opened. The message given was: {1}{0}.
        /// </summary>
        internal static string CannotOpenDatabase {
            get {
                return ResourceManager.GetString("CannotOpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot upgrade the database to version {0}.
        /// </summary>
        internal static string CannotUpgradeDatabaseToVersion {
            get {
                return ResourceManager.GetString("CannotUpgradeDatabaseToVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary \&quot;{0}\&quot; could not be loaded: perhaps the file has been moved or deleted?.
        /// </summary>
        internal static string CouldNotLoadDictionary {
            get {
                return ResourceManager.GetString("CouldNotLoadDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening dictionary.
        /// </summary>
        internal static string CouldNotLoadDictionaryCaption {
            get {
                return ResourceManager.GetString("CouldNotLoadDictionaryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file required for this program to run, {0}, was not found. To run this program from a zip file, please extract the entire zip file..
        /// </summary>
        internal static string DllNotFound {
            get {
                return ResourceManager.GetString("DllNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; was not found. Perhaps it was deleted or moved elsewhere?{2}{1}.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import failed with the message: {1}{0}.
        /// </summary>
        internal static string ImportFailedWithMessage {
            get {
                return ResourceManager.GetString("ImportFailedWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import had not begun..
        /// </summary>
        internal static string ImportHadNotBegun {
            get {
                return ResourceManager.GetString("ImportHadNotBegun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program data was created by a newer version of this program. Please upgrade {0} to the latest version to use the program..
        /// </summary>
        internal static string NewerDatabaseVersion {
            get {
                return ResourceManager.GetString("NewerDatabaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was cancelled..
        /// </summary>
        internal static string TheOperationWasCancelled {
            get {
                return ResourceManager.GetString("TheOperationWasCancelled", resourceCulture);
            }
        }
    }
}
