//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szotar.WindowsForms.Resources {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class DictionaryInfo {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal DictionaryInfo() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szotar.WindowsForms.Resources.Strings.DictionaryInfo", typeof(DictionaryInfo).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The name of the person or people who made the dictionary..
		/// </summary>
		internal static string Author_Description {
			get {
				return ResourceManager.GetString("Author.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Author.
		/// </summary>
		internal static string Author_DisplayName {
			get {
				return ResourceManager.GetString("Author.DisplayName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Information.
		/// </summary>
		internal static string Category_Information {
			get {
				return ResourceManager.GetString("Category.Information", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Source Information.
		/// </summary>
		internal static string Category_SourceInfo {
			get {
				return ResourceManager.GetString("Category.SourceInfo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Target Information.
		/// </summary>
		internal static string Category_TargetInfo {
			get {
				return ResourceManager.GetString("Category.TargetInfo", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The character encoding in which the dictionary is saved. Variable length encodings are supported, provided that the length of each record (in bytes) when encoded does not exceed the Entry Length..
		/// </summary>
		internal static string Encoding_Description {
			get {
				return ResourceManager.GetString("Encoding.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Character Encoding.
		/// </summary>
		internal static string Encoding_DisplayName {
			get {
				return ResourceManager.GetString("Encoding.DisplayName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The name of the dictionary..
		/// </summary>
		internal static string Name_Description {
			get {
				return ResourceManager.GetString("Name.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		internal static string Name_DisplayName {
			get {
				return ResourceManager.GetString("Name.DisplayName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The path of the actual file containing the dictionary entries. This is usually relative to the application directory or the Application Data directory..
		/// </summary>
		internal static string Path_Description {
			get {
				return ResourceManager.GetString("Path.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Path.
		/// </summary>
		internal static string Path_DisplayName {
			get {
				return ResourceManager.GetString("Path.DisplayName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The ISO-639-1 language code for the source language..
		/// </summary>
		internal static string SourceLanguage_Description {
			get {
				return ResourceManager.GetString("SourceLanguage.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Source Language.
		/// </summary>
		internal static string SourceLanguage_DisplayName {
			get {
				return ResourceManager.GetString("SourceLanguage.DisplayName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The length of each record in the dictionary file (in bytes). Don&apos;t change unless you know what you&apos;re doing..
		/// </summary>
		internal static string SourceStride_Description {
			get {
				return ResourceManager.GetString("SourceStride.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Source Entry Length.
		/// </summary>
		internal static string SourceStride_DisplayName {
			get {
				return ResourceManager.GetString("SourceStride.DisplayName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The ISO-639-1 language code from the target language..
		/// </summary>
		internal static string TargetLanguage_Description {
			get {
				return ResourceManager.GetString("TargetLanguage.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Target Language.
		/// </summary>
		internal static string TargetLanguage_DisplayName {
			get {
				return ResourceManager.GetString("TargetLanguage.DisplayName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The length of each record in the dictionary file (in bytes). Don&apos;t change unless you know what you&apos;re doing..
		/// </summary>
		internal static string TargetStride_Description {
			get {
				return ResourceManager.GetString("TargetStride.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Target Entry Length.
		/// </summary>
		internal static string TargetStride_DisplayName {
			get {
				return ResourceManager.GetString("TargetStride.DisplayName", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The dictionary&apos;s or creator&apos;s website..
		/// </summary>
		internal static string Url_Description {
			get {
				return ResourceManager.GetString("Url.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Website.
		/// </summary>
		internal static string Url_DisplayName {
			get {
				return ResourceManager.GetString("Url.DisplayName", resourceCulture);
			}
		}
	}
}
