//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szotar.WindowsForms.Resources {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class SimpleDictionary {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal SimpleDictionary() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asztal.Szótár.Resources.SimpleDictionary", typeof(SimpleDictionary).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Original author of the dictionary, before it was imported..
		/// </summary>
		internal static string Author_Description {
			get {
				return ResourceManager.GetString("Author.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Author.
		/// </summary>
		internal static string Author_Name {
			get {
				return ResourceManager.GetString("Author.Name", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name of this dictionary (e.g. English-French)..
		/// </summary>
		internal static string Name_Description {
			get {
				return ResourceManager.GetString("Name.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Dictionary Name.
		/// </summary>
		internal static string Name_Name {
			get {
				return ResourceManager.GetString("Name.Name", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to A website related to the dictionary (preferably from which the dictionary can be downloaded).
		/// </summary>
		internal static string Url_Description {
			get {
				return ResourceManager.GetString("Url.Description", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to URL.
		/// </summary>
		internal static string Url_Name {
			get {
				return ResourceManager.GetString("Url.Name", resourceCulture);
			}
		}
	}
}
