//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szotar.WindowsForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szotar.WindowsForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Begin.
        /// </summary>
        internal static string BeginCommand {
            get {
                return ResourceManager.GetString("BeginCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change item to &apos;{0}&apos; and &apos;{1}&apos;.
        /// </summary>
        internal static string ChangedItemToXandY {
            get {
                return ResourceManager.GetString("ChangedItemToXandY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string ChangedXToY {
            get {
                return ResourceManager.GetString("ChangedXToY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this word list? This operation cannot be undone..
        /// </summary>
        internal static string ConfirmDeleteWordList {
            get {
                return ResourceManager.GetString("ConfirmDeleteWordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deleting word list.
        /// </summary>
        internal static string ConfirmDeleteWordListCaption {
            get {
                return ResourceManager.GetString("ConfirmDeleteWordListCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This word list has does not have any entries. Do you want to save it anyway? (Pressing &apos;No&apos; will delete this word list.).
        /// </summary>
        internal static string ConfirmKeepNewWordList {
            get {
                return ResourceManager.GetString("ConfirmKeepNewWordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep this word list?.
        /// </summary>
        internal static string ConfirmKeepNewWordListCaption {
            get {
                return ResourceManager.GetString("ConfirmKeepNewWordListCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string DefaultDictionaryName {
            get {
                return ResourceManager.GetString("DefaultDictionaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string DefaultListName {
            get {
                return ResourceManager.GetString("DefaultListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultListStoreName {
            get {
                return ResourceManager.GetString("DefaultListStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} items.
        /// </summary>
        internal static string DeletedNItems {
            get {
                return ResourceManager.GetString("DeletedNItems", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon DictionaryIcon {
            get {
                object obj = ResourceManager.GetObject("DictionaryIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the file for the first half of the dictionary..
        /// </summary>
        internal static string DictionarySectionSelectFirstHalf {
            get {
                return ResourceManager.GetString("DictionarySectionSelectFirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the file for the second half of the dictionary..
        /// </summary>
        internal static string DictionarySectionSelectSecondHalf {
            get {
                return ResourceManager.GetString("DictionarySectionSelectSecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Finish.
        /// </summary>
        internal static string FinishCommand {
            get {
                return ResourceManager.GetString("FinishCommand", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Floppy48 {
            get {
                object obj = ResourceManager.GetObject("Floppy48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GenericDocument16 {
            get {
                object obj = ResourceManager.GetObject("GenericDocument16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GenericDocument96 {
            get {
                object obj = ResourceManager.GetObject("GenericDocument96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Finished.
        /// </summary>
        internal static string ImportFinished {
            get {
                return ResourceManager.GetString("ImportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert 1 item.
        /// </summary>
        internal static string Inserted1Item {
            get {
                return ResourceManager.GetString("Inserted1Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert {0} items.
        /// </summary>
        internal static string InsertedNItems {
            get {
                return ResourceManager.GetString("InsertedNItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Internal Operation).
        /// </summary>
        internal static string InternalOperation {
            get {
                return ResourceManager.GetString("InternalOperation", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap List48 {
            get {
                object obj = ResourceManager.GetObject("List48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next.
        /// </summary>
        internal static string NextCommand {
            get {
                return ResourceManager.GetString("NextCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} terms.
        /// </summary>
        internal static string NTerms {
            get {
                return ResourceManager.GetString("NTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} results are shown. Double-click here to show more..
        /// </summary>
        internal static string OnlyNResultsShown {
            get {
                return ResourceManager.GetString("OnlyNResultsShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase.
        /// </summary>
        internal static string PhraseDefaultHeader {
            get {
                return ResourceManager.GetString("PhraseDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Lists.
        /// </summary>
        internal static string RecentListStoreName {
            get {
                return ResourceManager.GetString("RecentListStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo &quot;{0}&quot;.
        /// </summary>
        internal static string RedoSpecific {
            get {
                return ResourceManager.GetString("RedoSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string SortedList {
            get {
                return ResourceManager.GetString("SortedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap {0} rows.
        /// </summary>
        internal static string SwappedNRows {
            get {
                return ResourceManager.GetString("SwappedNRows", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap TopInwardShadow {
            get {
                object obj = ResourceManager.GetObject("TopInwardShadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        internal static string TranslationDefaultHeader {
            get {
                return ResourceManager.GetString("TranslationDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo &quot;{0}&quot;.
        /// </summary>
        internal static string UndoSpecific {
            get {
                return ResourceManager.GetString("UndoSpecific", resourceCulture);
            }
        }
    }
}
